baseURL = "https://keltonsantos.github.io/data_science_portfolio/"
locale = "en-AU"
title = "Kelton Santos | ML & Data Science"
theme = "congo"

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"
