baseURL = "https://keltonsantos.github.io/data_science_portfolio/"
locale = "en-US"
title = "Kelton Santos"
theme = "congo"

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"
